### ISSUE TITLE
tip-lib-0.1 doesn't compile because alex isn't listed as a build-tool

### ISSUE THREAD

**Issue by peti** [tip-org/benchmarks#1]
Citing from http://hydra.cryp.to/build/926186/log/raw:

```
Building tip-lib-0.1...
Preprocessing library tip-lib-0.1...
Setup: The program 'alex' is required but it could not be found
```

It would be great if a `build-tools` stanza listing `alex` could be added to the Cabal file.

**Comment by danr** [comment]
Thanks. I was unaware that `cabal sdist` bundled the alex and happy files instead of the generated haskell files. This shold now be fixed in version 0.1.1.
