### ISSUE TITLE
Why are there true propositions in false/ ?

### ISSUE THREAD

**Issue by djeis97** [tip-org/benchmarks#11]
According to the README the problems in the false/ subdir should all be false propositions for counterexample finding, but there seem to be a few true ones in there as well. In particular the one that surprised me was `productive_use_of_failure_app_inj1` as a straightforward translation of it into Coq produced a statement which is trivial to prove by induction on xs. The lemma as stated also seems intuitively true to me: with the first argument fixed, append should be injective. I admit a lack of experience in the SMT tools which TIP normally targets, so perhaps I'm seriously misunderstanding something here. Could someone with more experience on this project care to comment?

**Comment by nick8325** [comment]
Not sure how that got in (and some other false ones too). Should be fixed now. Thanks!
