### ISSUE TITLE
Invalid match patterns order

### ISSUE THREAD

**Issue by Columpio** [tip-org/benchmarks#13]
The SMTLIB2 specification fixes top-down order of pattern comparison in `match` terms ([see](http://smtlib.cs.uiowa.edu/papers/smt-lib-reference-v2.6-r2017-07-18.pdf) sec. 3.6.1, after Remark 4).
In the generated benchmark however we obtain:
```smt
(match x
    ((_ false)
     (ESC true)
     (P true)
     (Q true)
     (R true)))
```
(taken from [benchmark](https://github.com/tip-org/benchmarks/blob/master/benchmarks/tip2015/escape_NoSpecial.smt2)).
This forces pattern matching to follow the first `_` clause.

**Comment by nick8325** [comment]
Should be fixed now!
