### ISSUE TITLE
Empty benchmarks

### ISSUE THREAD

**Issue by danr** [tip-org/benchmarks#4]
For instance list_z_elem.
https://github.com/tip-org/benchmarks/blob/master/benchmarks/tip2015/list_z_elem.smt2

**Comment by aztek** [comment]
I found these ones:
`tip2015/list_z_elem_map.smt2`
`tip2015/list_z_elem.smt2`
`tip2015/list_elem_map.smt2`
`tip2015/list_elem.smt2`
by sorting all the files in the directory by size.

**Comment by nick8325** [comment]
Seems to be fixed now.
