### ISSUE TITLE
spurious `@` in some benchmarks?

### ISSUE THREAD

**Issue by c-cube** [tip-org/benchmarks#5]
Some problems, e.g. `benchmarks/isaplanner/prop_12.smt2`, contain the symbol `@`, which is not declared. I am not very familiar with smtlib2 but I don't think it is a special keyword.

**Comment by nick8325** [comment]
This is our extension for first-class functions - `@` is the application operator. Unfortunately the documentation for the TIP language is rather sparse but you can find it described at http://www.cse.chalmers.se/~nicsma/papers/tip-tools.pdf.

If you run `tip --lambda-lift --axiomatize-lambdas`, all uses of `@` will be axiomatised away. You can also look in the `benchmarks-cvc4` directory for versions of the benchmarks which have been translated to more standard smtlib2.

**Comment by c-cube** [comment]
My bad, thanks.
